### ISSUE TITLE
How can i change the data from Chinese to English?

### ISSUE THREAD

**Issue by JancoBH** [VernonLee/Theogony#1]
Hello, Thanks for publish how to use the Riot Api, I want to create an App using this and it will help me alot.

I want to know how to change the data from Chinese to English? 

Thanks =D

**Comment by VernonLee** [comment]
Hi ! Just modify [Locale](https://github.com/VernonLee/Theogony/blob/master/riotgamesapi/src/main/java/com/nodlee/riotgames/Locale.java).getDefaultLocaleCode() method like this:

```
    public static String getDefaultLocaleCode() {
        return getLocaleCode(3);
    }

```

**Comment by JancoBH** [comment]
Thanks, I did that yesterday but it doesn't work and I asked it to be sure because you wrote "the default lenguage is chinese" and my problem was that I had to uninstall and re-install the app because it wasn't downloading the data. 

Thanks ,  I want to create and league of legends app like a wiki (gettin items, rotate champs, etc) and your repository will help me alot.
